### ISSUE TITLE
Elkészültem a beadandó feladattal

### ISSUE THREAD

**Issue by ZoltanTozser** [Teaching-projects/SZE-FordProg-2021-Fapados#1]

**Comment by hegyhati** [comment]
No, hat akkor megis parser generator lett belole. a json nem egy bonyolult valami, de ahgoy latom, szepen meg van csinalva, negyest meg tudom adni ra.

**Comment by ZoltanTozser** [comment]
Igen, parser generátor lett belőle, hallgattam rád, hogy ne "szaki" megoldás legyen belőle. A négyes jó lesz nekem, köszi. 
Fel is jelentkeztem az utolsó vizsgára.
Minden jót kívánok!

**Comment by hegyhati** [comment]
En pedig be is irtam, szep nyarat!
